config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, only: [:new, :create]

  get '/users/log_in' => "users#log_in", as: :log_in
  get '/users/profile' => "users#profile", as: :profile

  post   '/sessions' => "sessions#create", as: :create_session
  delete '/sessions' => "sessions#destroy", as: :delete_session

  resources :food_items
  resources :tables do
    resources :food_orders

  end

  get '/tables/:id/receipt/' => "tables#receipt", as: :receipt
  delete '/tables/:table_id/food_orders/' => "food_orders#destroy"

  resources :waitstaffs

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :waitstaff
  has_many :food_orders
  has_many :food_items, through: :food_orders


  #  attr_reader :party_size, :table_number
  

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  has_many :food_orders
  has_many :tables, through: :food_orders
end

app/models/food_order.rb
class FoodOrder < ActiveRecord::Base
  belongs_to :food_item
  belongs_to :table
end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :waitstaff
  has_many :customers

  #  attr_reader :party_size, :table_number
  def makeCustomers(size)
    unless size == 0
      Customer.create
      size - 1
    end
  end

end

app/models/table.rb
class Table < ActiveRecord::Base
  belongs_to :waitstaff
  has_many :food_orders
  has_many :food_items, through: :food_orders
  validates :table_number, uniqueness: true

  #  attr_reader :party_size, :table_number
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
end

app/models/waitstaff.rb
class Waitstaff < ActiveRecord::Base
  has_many :tables
  has_many :food_orders, through: :tables

end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController

  before_action :authenticate!, except: [:index]

  def index
    @food_items = FoodItem.all
    @user = current_user
  end
  def new
    @food_item = FoodItem.new
  end
  def create
    newFood = FoodItem.create food_params
    redirect_to food_items_path
  end

  def edit
    @food_item = FoodItem.find params[:id]
  end

  def show
    @food_item = FoodItem.find params[:id]
  end

  def update
    food_item = FoodItem.find params[:id]
    food_item.update food_params
    redirect_to food_item_path food_item.id
  end

  def destroy
    FoodItem.destroy params[:id]
    redirect_to food_items_path
  end

  private

  def food_params
    params.require(:food_item).permit(:name, :category, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      # debugger
      # get the field from the form
      username = params[:username]
      password = params[:password]

      user = User.find_by username: username

      if user && user.authenticate( password )
        session[:user_id] = user.id
        redirect_to profile_path
      else
        redirect_to log_in_path
      end
    end

    # destroy a session
    def destroy
      session[:user_id] = nil
      redirect_to root_path
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :authenticate!

  def index
    @tables = Table.all
    # @othertables = Table.uniq.pluck(:table_number)
  end

  def create
    newTable = Table.create table_params
    redirect_to "#{table_path(newTable)}/food_orders/new"
  end

  def new
    @table = Table.new
  end

  def edit
    @table = Table.find params[:id]
  end

  def show
    @table = Table.find params[:id]
    @food_orders = FoodOrder.where(table_id: params[:id])
  end

  def receipt
    @table = Table.find params[:id]
    @food_orders = FoodOrder.where(table_id: params[:id])
  end

  def update
    table = Table.find params[:id]
    table.update table_params
    redirect_to table_path table.id
  end



  def destroy
    Table.destroy params[:id]
    redirect_to tables_path
  end



  private

  def table_params
    params.require(:table).permit(:table_number, :waitstaff_id, :is_paid, :to_display)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # include SessionsHelper
  before_action :authenticate_home!, only: [:profile]

  def new
    @user = User.new
  end

  def create
    user = User.create user_params
    redirect_to log_in_path
  end

  def log_in

  end

  def profile
    @user = current_user

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :is_admin)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/food_orders_helper.rb
module FoodOrdersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def authenticate!
    redirect_to log_in_path unless current_user
  end

  def authenticate_home!
    redirect_to root_path unless current_user 
  end

  def current_user
    @current_user = User.find session[:user_id] if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waitstaffs_helper.rb
module WaitstaffsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tables/edit.html.erb
<h1>EDIT TABLE</h1>

<%= form_for @table do |f| %>
  <%= f.label :table_number %>
  <%= f.number_field :table_number %>


  <%= f.label :waitstaffs_id %>
  <%= f.collection_select :waitstaffs_id, Waitstaff.all, :id, :name %>

  <%= f.submit %>
<% end %>

<%= link_to "DELETE", table_path(@table), method: :delete %>

app/views/tables/index.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Log Out", delete_session_path, method: :delete %></li>

  </ul>
</header>
<h2>Current Customers</h2>
<div>
<%= link_to "Add a new table", new_table_path %>
</div>
<% @tables.each do |table| %>
  <div class= "col-sm-3">
  <h4>Table <%= table.table_number%></h4>
  <p>Server - <%= table.waitstaff.name %></p>

  <h6><div class="col-xs-12"><%= link_to "Add Order", new_table_food_order_path(table) %> | <%= link_to "View Orders", table_path(table) %> | <%= link_to "Receipt", receipt_path(table) %> | <%= link_to "Close Out", table_path(table), method: :delete %></div></h6>
</div>
<% end %>



<!--  loop through table numbers, make those the headers, show the customers under each table as editable fields-->

app/views/tables/new.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Log Out", delete_session_path, method: :delete %></li>

  </ul>
</header>
<h1>NEW TABLE</h1>


<%= form_for @table do |f| %>
  <%= f.label :table_number %>
  <%= f.number_field :table_number %>



  <%= f.label :waitstaff_id %>
  <%= f.collection_select :waitstaff_id, Waitstaff.all, :id, :name %>

  <%= f.submit %>

<% end %>

app/views/tables/receipt.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Log Out", delete_session_path, method: :delete %></li>

  </ul>
</header>
<h1>Table <%= @table.table_number%></h1>
<h4>Orders:</h4>
<%total = 0%>
<% @food_orders.each do |o|%>
<div class="row">
  <div class="col-xs-6">
<p><%= o.food_item.name %></p>
</div>
<div class="col-xs-6">

<p><%= number_to_currency(o.food_item.price) %></p>
</div>
</div>
<% total = total + o.food_item.price %>
<% end %>
<div class="col-xs-6">
</div>
  <div class="col-xs-6">

<h4>Total <%=number_to_currency(total)%></h4>
</div>
<%tip25 = total * 0.25%>
<%tip20 = total * 0.2%>
<%tip15 = total * 0.15%>
<div class="row">
  <div class="col-xs-3">
  </div>
<div class="col-xs-6">

<p class="tip">15% Tip is <%=number_to_currency(tip25)%></p>
</div>
</div>
<div class="row">
  <div class="col-xs-3">
  </div>
<div class="col-xs-6">

<p class="tip">20% Tip is <%=number_to_currency(tip20)%></p>
</div>
</div>
<div class="row">
  <div class="col-xs-3">
  </div>
<div class="col-xs-6">

<p class="tip">25% Tip is <%=number_to_currency(tip15)%></p>
</div>
</div>


<h4><%= link_to "Close Out", table_path(@table), method: :delete %></h4>

app/views/tables/show.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Log Out", delete_session_path, method: :delete %></li>

  </ul>
</header>
<h1>Table <%= @table.table_number%></h1>
<div class="row">
<div class="col-xs-5">
<p>Item</p>
</div>
<div class="col-xs-5">
  <p>Seat Number</p>
</div>
</div>
<% @food_orders.each do |o|%>
<div class="row">
<div class="col-xs-5">
<p><%= o.food_item.name %></p>
</div>
<div class="col-xs-5">
  <p><%= o.seat_number %></p>
</div>
</div>
<% end %>

<h6><div class="col-xs-12"><%= link_to "Add Order", new_table_food_order_path(params[:id]) %> | <%= link_to "Receipt", receipt_path %> | <%= link_to "Close Out", table_path(@table), method: :delete %></div></h6>