config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users, only: [:new, :create]

  get '/users/log_in' => "users#log_in", as: :log_in
  get '/users/profile' => "users#profile", as: :profile

  post   '/sessions' => "sessions#create", as: :create_session
  delete '/sessions' => "sessions#destroy", as: :delete_session

  resources :food_items
  resources :tables do
    resources :food_orders

  end

  get '/tables/:id/receipt/' => "tables#receipt", as: :receipt
  delete '/tables/:table_id/food_orders/' => "food_orders#destroy"

  resources :waitstaffs

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :waitstaff
  has_many :food_orders
  has_many :food_items, through: :food_orders


  #  attr_reader :party_size, :table_number
  

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  has_many :food_orders
  has_many :tables, through: :food_orders
end

app/models/food_order.rb
class FoodOrder < ActiveRecord::Base
  belongs_to :food_item
  belongs_to :table
end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :waitstaff
  has_many :customers

  #  attr_reader :party_size, :table_number
  def makeCustomers(size)
    unless size == 0
      Customer.create
      size - 1
    end
  end

end

app/models/table.rb
class Table < ActiveRecord::Base
  belongs_to :waitstaff
  has_many :food_orders
  has_many :food_items, through: :food_orders
  validates :table_number, uniqueness: true

  #  attr_reader :party_size, :table_number
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
end

app/models/waitstaff.rb
class Waitstaff < ActiveRecord::Base
  has_many :tables
  has_many :food_orders, through: :tables

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper


end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController

  before_action :authenticate!, except: [:index]

  def index
    @food_items = FoodItem.all
    @user = current_user
  end
  def new
    @food_item = FoodItem.new
  end
  def create
    newFood = FoodItem.create food_params
    redirect_to food_items_path
  end

  def edit
    @food_item = FoodItem.find params[:id]
  end

  def show
    @food_item = FoodItem.find params[:id]
  end

  def update
    food_item = FoodItem.find params[:id]
    food_item.update food_params
    redirect_to food_item_path food_item.id
  end

  def destroy
    FoodItem.destroy params[:id]
    redirect_to food_items_path
  end

  private

  def food_params
    params.require(:food_item).permit(:name, :category, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      # debugger
      # get the field from the form
      username = params[:username]
      password = params[:password]

      user = User.find_by username: username

      if user && user.authenticate( password )
        session[:user_id] = user.id
        redirect_to profile_path
      else
        redirect_to log_in_path
      end
    end

    # destroy a session
    def destroy
      session[:user_id] = nil
      redirect_to root_path
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :authenticate!

  def index
    @tables = Table.all
    # @othertables = Table.uniq.pluck(:table_number)
  end

  def create
    newTable = Table.create table_params
    redirect_to "#{table_path(newTable)}/food_orders/new"
  end

  def new
    @table = Table.new
  end

  def edit
    @table = Table.find params[:id]
  end

  def show
    @table = Table.find params[:id]
    @food_orders = FoodOrder.where(table_id: params[:id])
  end

  def receipt
    @table = Table.find params[:id]
    @food_orders = FoodOrder.where(table_id: params[:id])
  end

  def update
    table = Table.find params[:id]
    table.update table_params
    redirect_to table_path table.id
  end



  def destroy
    Table.destroy params[:id]
    redirect_to tables_path
  end



  private

  def table_params
    params.require(:table).permit(:table_number, :waitstaff_id, :is_paid, :to_display)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # include SessionsHelper
  before_action :authenticate_home!, only: [:profile]

  def new
    @user = User.new
  end

  def create
    user = User.create user_params
    redirect_to log_in_path
  end

  def log_in

  end

  def profile
    @user = current_user

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :is_admin)
  end

end

app/controllers/waitstaffs_controller.rb
class WaitstaffsController < ApplicationController
  before_action :authenticate!

  def index
    @waitstaffs = Waitstaff.all
  end

  def create
    newStaff = Waitstaff.create staff_params
    redirect_to waitstaff_path
  end

  def new
    @waitstaff = Waitstaff.new
    @user = current_user

  end

  def edit
    @waitstaff = Waitstaff.find params[:id]
  end

  def show
    @waitstaff = Waitstaff.find params[:id]
    @tables =Table.where(waitstaff_id: params[:id])
  end

  def update
    waitstaff = Waitstaff.find params[:id]
    waitstaff.update staff_params
    redirect_to waitstaff_path waitstaff.id
  end

  def destroy
    Waitstaff.destroy params[:id]
    redirect_to waitstaffs_path
  end

  private

  def staff_params
    params.require(:waitstaff).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/food_orders_helper.rb
module FoodOrdersHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def authenticate!
    redirect_to log_in_path unless current_user
  end

  def authenticate_home!
    redirect_to root_path unless current_user 
  end

  def current_user
    @current_user = User.find session[:user_id] if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waitstaffs_helper.rb
module WaitstaffsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food_items/edit.html.erb
<h1>NEW Food</h1>

<%= form_for @food_item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :price %>
  <%= f.number_field :price, :step => 0.01 %>

  <%= f.submit %>
<% end %>

app/views/food_items/index.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
  </ul>
</header>
<h1>Menu</h1>
<%if @user && @user.is_admin == 1%>
<%= link_to "Add Food Item", new_food_item_path %>
<% end %>
<div class="menu-container">
<% @food_items.each do |food| %>
  <div class="row food-row">
    <div class="col-xs-6">
      <p><%= food.name %></p>
    </div>
    <div class="col-xs-3">
      <p><%= number_to_currency(food.price) %></p>
    </div>
    <%if @user && @user.is_admin == 1%>
    <div class="col-xs-3">

    <h4><%= link_to "Delete", food_item_path(food), method: :delete %></h4>
    </div>
    <% else %>
    <div class="col-xs-3">
    </div>
  <% end %>
</div>

<% end %>
</div>

app/views/food_items/new.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
  </ul>
</header>
<h1>NEW Food</h1>

<%= form_for @food_item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :price %>
  <%= f.number_field :price, :step => 0.01 %>

  <%= f.submit %>
<% end %>

app/views/users/log_in.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Menu", food_items_path %></li>
  </ul>
</header>
<h1>Log In Here</h1>

<%= form_tag '/sessions', method: :post do %>

  <%= label_tag :username %>
  <%= text_field_tag :username %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Log In" %>

<% end %>

<%= link_to "Create a new user", new_user_path %>

app/views/users/new.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Menu", food_items_path %></li>
  </ul>
</header>
<h1>Create a new user!</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <!-- note that this is a password field, dont mess this up! -->
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.radio_button :is_admin, 0%>Not Admin
  <%= f.radio_button :is_admin, 1%>Admin
  <!-- <%= f.radio_button :is_admin, "Admin", :checked => "1" %> -->

  <%= f.submit %>
<% end %>

app/views/users/profile.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Log Out", delete_session_path, method: :delete %></li>

  </ul>
</header>
<h1>Welcome Back <%= @user.username %></h1>

<li><%= link_to "View Tables", tables_path %></li>
<li><%= link_to "View Menu", food_items_path %></li>

<% if @user.is_admin == 1%>
  <li><%= link_to "View Staff", waitstaffs_path %></li>

<% end %>

app/views/waitstaffs/index.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Log Out", delete_session_path, method: :delete %></li>

  </ul>
</header>
<h1>Staff List</h1>

<div class="shift-button"><%= link_to "Start a New Shift", new_waitstaff_path %></div>
  <% @waitstaffs.each do |staff| %>
  <div class="col-sm-3 has-border">
    <h4><%= staff.name %></h4>
    <%if staff.tables.length > 0%>
      <p>Serving:</p>
        <ul>
          <%staff.tables.each do |t|%>
          <li>Table <%= t.table_number %></li>
          <% end %>
        </ul>
    <%else%>
      <%= button_to "End Shift", waitstaff_path(staff), method: :delete %>
    <% end %>
  </div>
  <% end %>

app/views/waitstaffs/new.html.erb
<header>
  <ul>
    <li><%= link_to "Home", profile_path%></li>
    <li><%= link_to "Log Out", delete_session_path, method: :delete %></li>

  </ul>
</header>
<h1>Staff</h1>

<%= form_for @waitstaff do |f| %>

  <%= f.label :name, value: "Employee Name" %>
  <%= f.text_field :name, value: @user.username %>

  <%= f.submit "Start Shift"%>
<% end %>